version: '3.3'
services:
  postgresql:
    image: postgres:10.4
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080